---
version: "3.8"
services:
  hapifhir:
    image: hapiproject/hapi:latest
    hostname: hapifhir
    container_name: hapifhir
    ports:
      - "8888:8080"
    networks:
      - my-network

  zookeeper:
    image: strimzi/kafka:0.11.4-kafka-2.1.0
    hostname: zookeeper
    container_name: zookeeper
    command: [
        "sh", "-c",
        "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
    networks:
      - my-network

  kafka:
    image: strimzi/kafka:0.11.4-kafka-2.1.0
    hostname: kafka
    container_name: kafka
    command: [
        "sh", "-c",
        "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - my-network

  iDAAS-Connect:
    image: docker.io/maven:3.6.3-jdk-8
    hostname: iDAAS-Connect-BlueButton
    container_name: iDAAS-Connect-BlueButton
    environment:
      MAVEN_CONFIG: /tmp/.m2
    command: [
        "sh", "-c",
        "mvn clean compile spring-boot:run -Didaas.kafkaBrokers=kafka:9092 -Dserver.port=8089 -Dmaven.repo.local=/tmp/.m2/repository"
    ]
    volumes:
      - "./:/workspace:Z,delegated"
      # Mounting user's local .m2-directory,
      # for custom settings.xml and for caching dependencies.
      - "~/.m2/repository:/tmp/.m2/repository:Z,delegated"
    working_dir: /workspace
    ports:
      - "8089:8089"
    depends_on:
      - hapifhir
      - kafka
    networks:
      - my-network
networks:
  my-network:
    name: idaasconnect-bb-network
