name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to checkout when cutting the release."
        required: true
        default: "master"
      increment-major:
        description: "Should we increment the major version (true/false)"
        required: true
        default: "false"
      increment-minor:
        description: "Should we increment the minor version (true/false)"
        required: true
        default: "false"

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.IDAAS_ACCESS_TOKEN }}
    - name: Java Maven release
      uses: qcastel/github-actions-maven-release@v1.12.16
      env:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
      with:
        access-token: ${{ secrets.IDAAS_ACCESS_TOKEN }}
        release-branch-name: ${{ github.event.inputs.branch }}
        version-major: ${{ github.event.inputs.increment-major }}
        version-minor: ${{ github.event.inputs.increment-minor }}
        maven-args: "-Dmaven.deploy.skip=true"
        git-release-bot-name: "idaas-bot"
